### ISSUE TITLE
Is put_beeper() implemented?

### ISSUE THREAD

**Issue by friscodelrosario** [mpru/karel#1]
generate_world("mundo001")
karel_has_beepers()
[1] TRUE
put_beeper()
karel_has_beepers()

expected FALSE
got  TRUE

**Comment by friscodelrosario** [comment]
> generate_world("mundo001")
> turn_left()
> move()
> turn_left()
> turn_left()
> turn_left()
> move()
> move()
> move()
> move()
> move()
> facing_east()
[1] TRUE
> front_is_blocked()
[1] TRUE
> run_actions() //worked!
                                                                              
Inserting image 11 at 5.00s (100%)...
Encoding to gif... done!
> 
![Screenshot_2023-03-18_16-36-38](https://user-images.githubusercontent.com/59985/226145585-4852aef8-25cd-45dd-b0d6-3f7aa70dcbc4.png)

**Comment by mpru** [comment]
Hi! Sorry for not replying before.

I'm glad you made it work, but I'd like to add a comment. put_beeper() is implemented and it reduces by one the number of bippers Karel has on its bag. The initial number of beepers dependes in the world. In this world, Karel starts with an infinite number of beepers in its bag, so karel_has_beepers() will always return TRUE, even if you run put_beepers() several times.

Thanks for your message.
