### ISSUE TITLE
use newer pkgdown templates?

### ISSUE THREAD

**Issue by maelle** [mpru/karel#10]
See https://pkgdown.r-lib.org/articles/customise.html#getting-started

With this, in particular the font will be bigger. :wink: :mag:

**Comment by mpru** [comment]
Thanks for the suggestion! I had used Bootstrap 5 before and then gone back to 3 because I didn't completely like having the toc at the bottom of each page instead of having it at the right as it was before, and couldn't figure out how to move it. Anyway, following your advice now I went back to a newer template. Thanks!

**Comment by maelle** [comment]
oh, weird that the TOC was at the bottom of the page!

**Comment by mpru** [comment]
I mean the "On this page" box that with the previous templates was always at the right and now is always on the bottom... All the pkgdown websites for the tidyverse packages I've seen recently have it at the bottom as well. But I'm sure there's a good reason for that.

**Comment by maelle** [comment]
ooooh do you mean on "narrow" screens?

**Comment by mpru** [comment]
I thought it had to do with customization for the size of the screen, but isn't it like that in wide screens, too? I've tried in two wide screens and I saw it shown in  the bottom as well, like in this [screenshot](https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html) from ggplot2 website. Nevertheless, thanks for engaging with me in this conversation, I wouldn't like to waste your time in something minor. 

![image](https://github.com/mpru/karel/assets/7343551/ac517e42-1cc6-4613-89be-d2b46441bc55)

**Comment by maelle** [comment]
It's not minor, it could be a pkgdown bug, could you please open an issue there, and add your browser, OS + maybe look whether there's any error in the web developer console (see https://rmd-blogging-blr.netlify.app/webdev/devtools/ -- or ping me in the rOpenSci slack at the end of August)? thanks so much for this.

**Comment by maelle** [comment]
there = https://github.com/r-lib/pkgdown
