### ISSUE TITLE
Update repo metadata

### ISSUE THREAD

**Issue by LukasWallrich** [mpru/karel#3]
When I open a repo, I tend to look first at the information to see the webpage and licencing info - those are currently not visible in yours ... might be worth adding.

<img width="388" alt="Screenshot 2023-04-20 at 16 22 36" src="https://user-images.githubusercontent.com/60155545/233413897-e8f130ac-e15a-4f81-9b87-d89d8016aac8.png">

**Comment by mpru** [comment]
Done!
